#!/usr/bin/env bash
# this file transfers a file from local machine to set server

if [ $# -lt 3  ]
    then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    else

#scp filename user@ipaddress:path_to_store_file
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
